---
abstract: 'Generate lists lazily'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  Test::Warn: '0'
  blib: '1.01'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: List-Lazy
provides:
  List::Lazy:
    file: lib/List/Lazy.pm
    version: v0.3.0
requires:
  Carp: '0'
  Clone: '0'
  Exporter::Tiny: '0'
  List::MoreUtils: '0'
  Moo: '0'
  MooX::HandlesVia: '0'
  experimental: '0'
  perl: v5.22.0
resources:
  bugtracker: https://github.com/yanick/List-Lazy/issues
  homepage: https://github.com/yanick/List-Lazy
  repository: https://github.com/yanick/List-Lazy.git
version: 0.3.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Yanick Champoux <yanick@cpan.org>'
x_serialization_backend: 'YAML::Tiny version 1.69'
